### PR TITLE
Feature/modrinth publishing

### PR DESCRIPTION
**Pull request by Aaron2550**
Only needs the Modrinth Token in the env var $MODRINTH_TOKEN, and we should be good to go! Allows us to publish a new version using `gradle modrinth`

### CODE REVIEW

**Comment by OoLunar** [comment]
I'll have the Release CI workflow call `gradle modrinth` with the token, then I'll merge.

**Review by OoLunar — APPROVED** [review]
LGTM, besides the broken git lol

**Comment by OoLunar** [comment]
Just to reiterate:

**The `gradle modrinth` command has been added:**
This allows for us to publish a mod to modrinth manually when we supply the `MODRINTH_TOKEN` as an environment variable.

**The Github Release workflow has been added:**
When a new Github Release has been created, the workflow will upload the artifact to the action, modify the Github Release to include the artifact and publish the artifact to Modrinth. By utilizing `sed`, the `gradle.properties` will be updated to use the tag used in the Github Release. Additionally, also through `sed`, the `build.gradle` will be modified to include the Github Release body as the changelog for the Modrinth upload.

---

Once the conflicts have been resolved, are we free to merge?

**Comment by Aaron2550** [comment]
LGTM, LGTM

looks good to me, lets get this merged

**Comment by InFTord** [comment]
LGTM :when:

**Comment by Aaron2550** [comment]
this too, is already merged my guy

**Comment by InFTord** [comment]
that's why i said that im late :D

**Pull request merged**
